name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "hai test msg"

      - name: prints new msg
        run: echo "msg print completed"
        
