name: second workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "test greeting"
      - name: print end msg
        run: echo "job execution done"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: test msg
        run: pip install smtplib
      - name: print end msg
        run: echo "smtplib installed successfully!
        
